const savingsGuide = 'https://www.moneysavingexpert.com/savings/savings-accounts-best-interest/';
const isaGuide = 'https://www.moneysavingexpert.com/savings/best-cash-isa/';
const investingGuide = 'https://www.moneysavingexpert.com/savings/stocks-shares-isas/';
const checked = '2026-10-05';
const cashProtection = 'Eligible deposits: FSCS up to £120,000 per person, per authorised institution. Shared licences count together; verify the named bank before depositing.';
const investmentProtection = 'No protection against market losses. FSCS investment protection may apply to eligible firm failures, not falling prices. Check the product structure.';
const currentAccountsGuide = 'https://www.moneysavingexpert.com/banking/compare-best-bank-accounts/';

function product(id, provider, name, category, options) {
  const isa = category.includes('ISAs');
  const adapter = { 'oxbury-saver': 'oxbury', 'shawbrook-isa': 'shawbrook-isa', 'plum-isa': 'plum-isa' }[id];
  if (adapter) options = { ...options, adapter };
  const newCustomers = ['zopa', 'chase-saver', 'oxbury-saver', 'saga-saver', 'monument-saver', 'plum-isa', 'moneybox-isa', 'trading-cash-isa'];
  const noNewRestriction = ['cynergy', 'cahoot', 'nsandi-saver', 'nsandi-isa', 'premium', 'charter-isa', 'shawbrook-isa', 'union-one', 'close-two', 'tesco-fixed', 'tesco-cash-isa', 'natwest-fixed-isa', 'oaknorth-fixed-isa', 'hodge-fixed-isa'];
  const appRequired = ['zopa', 'chase-saver', 'starling-saver', 'monument-saver', 'plum-isa', 'moneybox-isa', 'oxbury-saver'];
  const noAppRequired = ['cynergy', 'cahoot', 'union-one', 'close-two', 'nsandi-saver', 'nsandi-isa', 'premium', 'postoffice-saver', 'saga-saver', 'tesco-fixed', 'tesco-cash-isa', 'charter-isa', 'shawbrook-isa', 'boi-cash-isa', 'postoffice-cash-isa', 'leeds-cash-isa', 'natwest-fixed-isa', 'hodge-fixed-isa', 'oaknorth-fixed-isa', 'trading-cash-isa'];
  const transfersAccepted = ['plum-isa', 'moneybox-isa', 'charter-isa', 'shawbrook-isa', 'trading-cash-isa', 'boi-cash-isa', 'postoffice-cash-isa', 'leeds-cash-isa', 'natwest-fixed-isa', 'oaknorth-fixed-isa'];
  options = { customerEligibility: newCustomers.includes(id) ? 'new' : noNewRestriction.includes(id) ? 'any' : 'unknown', appRequired: appRequired.includes(id) ? true : noAppRequired.includes(id) ? false : null, requiresAnotherAccount: ['zopa', 'chase-saver', 'starling-saver'].includes(id) ? true : newCustomers.includes(id) || noNewRestriction.includes(id) ? false : null, acceptsTransfers: transfersAccepted.includes(id) ? true : id === 'hodge-fixed-isa' ? false : null, transferRate: { 'plum-isa': 3.75, 'trading-cash-isa': 3.6 }[id] ?? null, ...options };
  const isaOptions = isa ? { ...options, maximum: null, annualContributionLimit: category === 'Lifetime ISAs' ? 4000 : 20000 } : options;
  return { id, provider, name, category, risk: 'Cash', rate: null, rateKind: 'AER', minimum: 1, maximum: null, bonusMonths: 12, access: 'Easy access', protection: cashProtection, rateCheckedAt: checked, termsReviewedAt: checked, checkStatus: 'manual', fees: 'No account fee noted in the source; confirm current terms.', reviewUrl: `https://uk.trustpilot.com/search?query=${encodeURIComponent(provider)}`, editorialUrl: category === 'Cash ISAs' ? isaGuide : savingsGuide, ...isaOptions };
}

function currentAccountProduct(id, provider, name, options) {
  return {
    id, provider, name, category: 'Current accounts', risk: 'Cash', rate: null, rateKind: 'Current account rewards', minimum: 0, maximum: null,
    bonusMonths: 12, access: 'Everyday access', protection: cashProtection, rateCheckedAt: null, termsReviewedAt: '2026-10-08', checkStatus: 'manual',
    customerEligibility: 'any', appRequired: null, requiresAnotherAccount: false, acceptsTransfers: null,
    terms: options.currentAccount.eligibilityNotes, summary: options.currentAccount.summary,
    fees: `£${options.currentAccount.monthlyFee} monthly account fee, plus any charges in the provider's terms.`, editorialUrl: currentAccountsGuide,
    reviewUrl: `https://uk.trustpilot.com/search?query=${encodeURIComponent(provider)}`,
    ...options
  };
}

export const catalogue = [
  currentAccountProduct('nationwide-flexdirect', 'Nationwide', 'FlexDirect', {
    appRequired: false,
    sourceUrl: 'https://www.nationwide.co.uk/current-accounts/flexdirect/',
    currentAccount: {
      balanceAER: 5, balanceBonusMonths: 12, balanceBaseAER: 1, balanceCap: 1500, interestRequiresMonthlyPayIn: 1500, monthlyFee: 0,
      cashbackPrograms: [
        { id: 'spend', label: 'Eligible debit-card spending', rate: 1, spendSource: 'spend', minimumSpend: 500, monthlyCashbackCap: 5, minimumPayIn: 1500 },
        { id: 'bills', label: 'Direct Debit bills', fixedMonthlyCashback: 5, spendSource: 'bills', minimumSpend: 300, minimumDirectDebits: 1, minimumPayIn: 1500 }
      ],
      oneOffSwitchBonus: 175,
      eligibilityNotes: '5% balance interest for 12 months on up to £1,500 requires £1,500 monthly pay-in. £5 monthly debit-card and £5 monthly Direct Debit cashback have separate qualifying requirements. £175 switch offer has separate eligibility and CASS conditions.',
      overdraft: 'First £50 arranged overdraft interest-free; 39.9% EAR variable above that. Overdraft eligibility and limit are credit-checked.',
      summary: 'A building-society current account with balance interest and two separate cashback routes. The ongoing return depends on maintaining the monthly pay-in and meeting each reward condition.'
    }
  }),
  currentAccountProduct('chase-current', 'Chase', 'Current account', {
    appRequired: true, requiresAnotherAccount: true,
    sourceUrl: 'https://www.chase.co.uk/gb/en/product/chase-account/',
    currentAccount: {
      balanceAER: 0, balanceBonusMonths: 0, monthlyFee: 0,
      cashbackPrograms: [{ id: 'spend', label: 'Eligible card spending', rate: 2, spendSource: 'spend', monthlyCashbackCap: 20, minimumCardTransactions: 15, minimumLinkedSavings: 1000 }],
      oneOffSwitchBonus: null,
      eligibilityNotes: '2% cashback applies only to eligible purchase categories, requires 15 or more debit-card transactions a month and at least £1,000 in Chase savings. Cashback capped at £20 a month. Open the boosted linked saver within 31 days of opening the current account to qualify for its introductory rate.',
      linkedSavings: { name: 'Chase Saver', rate: 4.5, baseRate: 2.25, bonusRate: 2.25, bonusMonths: 12, maximum: 3000000, requiredOpenDays: 31 },
      overdraft: 'No arranged overdraft.',
      summary: 'An app-based current account. Its main estimated return here is category-limited debit-card cashback; the linked saver is calculated separately using the linked savings balance you enter.'
    }
  }),
  currentAccountProduct('santander-edge', 'Santander', 'Edge current account', {
    appRequired: false,
    sourceUrl: 'https://www.santander.co.uk/personal/current-accounts',
    currentAccount: {
      balanceAER: 0, balanceBonusMonths: 0, monthlyFee: 3, minimumMonthlyPayIn: 500,
      cashbackPrograms: [{ id: 'bills', label: 'Eligible household bills', rate: 1, spendSource: 'bills', monthlyCashbackCap: 10, minimumDirectDebits: 2, minimumPayIn: 500 }],
      oneOffSwitchBonus: null,
      eligibilityNotes: '£3 monthly fee. 1% cashback on eligible household bills paid by Direct Debit, up to £10 a month; £500 monthly pay-in and two or more eligible Direct Debits required.',
      linkedSavings: { name: 'Edge Saver', rate: 6, baseRate: 3.5, bonusRate: 2.5, bonusMonths: 12, maximum: 4000 },
        linkedSavings: { name: 'Edge Saver', rate: 6, baseRate: 3.5, bonusRate: 2.5, bonusMonths: 12, maximum: 4000, minimumMonthlyPayIn: 500, minimumDirectDebits: 2 },
      overdraft: '39.94% EAR variable; eligibility and limit are credit-checked.',
      summary: 'A high-street current account with a fee, household-bill cashback and a linked saver. Cashback only offsets the fee if the eligible bills and account conditions fit your actual usage.'
    }
  }),
  currentAccountProduct('zopa-biscuit', 'Zopa', 'Biscuit current account', {
    appRequired: true,
    sourceUrl: currentAccountsGuide,
    currentAccount: {
      balanceAER: 0, balanceBonusMonths: 0, monthlyFee: 0,
      cashbackPrograms: [{ id: 'bills', label: 'Chosen 3% cashback option', rate: 3, spendSource: 'bills', monthlySpendCap: 150 }],
      oneOffSwitchBonus: null,
      eligibilityNotes: 'Choose one rewards option at a time. This illustration models the 3% bills-cashback option on up to £150 eligible bills per month (maximum £54 a year). Other reward choices have different eligible spending categories.',
      overdraft: 'No overdraft included in this comparison; check current product terms.',
      summary: 'A digital current account. This comparison models the bills-cashback option only; choose and verify the available rewards option before applying.'
    }
  }),
  product('cynergy', 'Cynergy Bank', 'Online Easy Access Account', 'Savings', { rate: 4.55, maximum: 1000000, sourceUrl: 'https://www.cynergybank.co.uk/personal/online-easy-access-account', adapter: 'cynergy', terms: 'Variable rate includes a 12-month bonus. Unlimited withdrawals; online management. Check the current issue and bonus before opening.', summary: 'An online savings bank. Worth comparing for unrestricted access, but the introductory bonus needs a calendar reminder.' }),
  product('cahoot', 'Cahoot', 'Sunny Day Saver', 'Savings', { rate: 5, maximum: 3000, sourceUrl: 'https://www.cahoot.com/products-and-services/cahoot-sunny-day-saver', adapter: 'cahoot', terms: 'Up to £3,000 only. Variable rate; the account lasts 12 months. Cahoot is part of Santander, so check shared protection.', summary: 'Santander’s online banking brand. The small balance cap means the headline rate cannot apply to a whole £10,000 lump sum.' }),
  product('zopa', 'Zopa Bank', 'Bonus savings offer', 'Savings', { rate: 4.56, access: 'Limited access', maximum: 50000, sourceUrl: 'https://www.zopa.com/smart-saver', terms: 'New customers; open Smart Saver first. Introductory offer falls to 2% after more than three withdrawals a year. Verify offer availability.', summary: 'A digital bank with app-managed savings. The withdrawal restriction is the key drawback for money you may need often.' }),
  product('union-one', 'Union Bank of India UK', 'One-year fixed deposit', 'Savings', { rate: 5.12, minimum: 1000, maximum: 480000, access: 'Fixed term', sourceUrl: 'https://www.unionpremierbond.unionbankofindiauk.co.uk/Index.aspx', terms: 'Lock away for one year. Interest at maturity. Not suitable for emergency savings; verify the UK entity and deposit terms.', summary: 'The UK banking subsidiary, not the same protection arrangement as an overseas account. Check the exact legal entity and access terms.' }),
  product('close-two', 'Close Brothers', 'Two-year fixed-rate bond', 'Savings', { rate: 5.16, minimum: 10000, maximum: 2000000, access: 'Fixed term', sourceUrl: 'https://www.closesavings.co.uk/personal/savings-accounts/fixed-rate-bond/2-year', terms: 'Two-year commitment; £10,000 minimum. Annual interest paid away; withdrawals normally unavailable during the term.', summary: 'A specialist banking group. The minimum deposit and two-year lock matter more than a small rate advantage if you need access.' }),
  product('birmingham-notice', 'Birmingham Bank', '95-day notice savings', 'Savings', { rate: 4.4, minimum: 5000, maximum: 250000, access: 'Notice', sourceUrl: 'https://www.birminghambank.com/', terms: 'Give 95 days’ notice to withdraw; minimum £5,000. Confirm the live account issue and notice rules.', summary: 'A specialist bank rather than a household high-street name. Notice savings cannot replace immediately available emergency cash.' }),
  product('castle-notice', 'Castle Trust Bank', '120-day notice savings', 'Savings', { rate: 4.2, minimum: 1000, maximum: 500000, access: 'Notice', sourceUrl: 'https://www.castletrust.co.uk/savings', terms: 'Give 120 days’ notice to withdraw. Variable rate; check the live issue.', summary: 'A specialist savings provider. Only consider this access type for money you can plan to withdraw well in advance.' }),
  product('nsandi-saver', 'NS&I', 'Direct Saver', 'Savings', { rate: 3.75, maximum: 2000000, sourceUrl: 'https://www.nsandi.com/products/direct-saver', adapter: 'nsandi-aer', protection: '100% backed by HM Treasury, within the product’s balance limits.', terms: 'Variable rate, yearly interest. Withdrawals are not necessarily same-day; check processing times.', summary: 'Government-backed savings. The trade-off may be a lower rate than commercial savings accounts.' }),
  ...[
    { id: 'chase-saver', provider: 'Chase', name: 'New-customer boosted saver', rate: 4.5, maximum: 3000000, sourceUrl: 'https://www.chase.co.uk/gb/en/product/chase-saver-account/', terms: 'New customers; requires its free current account. Includes a 12-month bonus; app-managed, no joint accounts.', summary: 'Part of JPMorgan Chase. A recognisable banking group, but introductory eligibility and the expiry of the bonus still matter.' },
    { id: 'starling-saver', provider: 'Starling Bank', name: 'Easy Saver introductory offer', rate: 5, maximum: 25000, bonusMonths: 6, baseRate: 2.5, sourceUrl: 'https://www.starlingbank.com/savings/easy-saver/', terms: 'Requires its free current account. Headline rate applies for six months, then the published base rate is 2.5% variable. Both rates may change.', summary: 'An app-based UK bank. A six-month boost is not a full year at 5%; compare the whole-year illustration, not just the headline.' },
    { id: 'postoffice-saver', provider: 'Post Office', name: 'Online savings introductory offer', rate: 4.4, maximum: 2000000, sourceUrl: 'https://www.postoffice.co.uk/savings', terms: 'Online account; includes a one-year bonus over a 0.9% variable base rate. Monthly or annual interest; check the current issue and actual deposit bank.', summary: 'A familiar retail brand offering bank-provided savings. Protection follows the underlying bank and shared licence, not the Post Office name.' },
    { id: 'oxbury-saver', provider: 'Oxbury Bank', name: 'Easy Access Autumn account', rate: 4.3, minimum: 1000, maximum: 120000, sourceUrl: 'https://www.oxbury.com/savings-accounts/personal-savings/easy-access-autumn-account-issue-1-430-aer/', terms: 'New customers; no introductory bonus in the source. Online/app opening, app needed to manage; no joint accounts.', summary: 'A specialist UK bank. A straight variable rate avoids a short-term bonus expiry, but the minimum balance and app requirements still matter.' },
    { id: 'saga-saver', provider: 'Saga', name: 'New-customer easy-access offer', rate: 4.25, maximum: 1000000, sourceUrl: 'https://www.saga.co.uk/money/savings', terms: 'New customers; includes a one-year bonus. Online management; no joint accounts. Check provider eligibility and underlying deposit bank.', summary: 'A familiar consumer brand, rather than a reason to assume a separate banking licence. Check which bank holds the deposit.' },
    { id: 'monument-saver', provider: 'Monument Bank', name: 'New-customer easy-access offer', rate: 4.56, minimum: 25000, maximum: 2000000, sourceUrl: 'https://www.monument.co/', terms: 'Minimum £25,000. App-only; no joint accounts. Account lasts one year although the rate is variable.', summary: 'A digital savings bank with a high opening minimum. It cannot take a £10,000 comparison balance under these published conditions.' },
    { id: 'tesco-fixed', provider: 'Tesco Bank', name: 'Two-year fixed-rate saver', rate: 4.85, minimum: 2000, maximum: 5000000, access: 'Fixed term', sourceUrl: 'https://www.tescobank.com/savings/', terms: 'Two-year commitment. Source quotes 4.85% AER, or 4.75% gross for monthly paid-away interest. Check live product availability and withdrawal terms.', summary: 'A well-known brand. The current provider site identifies Tesco Bank as a trading name of Barclays Bank UK PLC; check shared deposit protection and do not treat the two-year fix as easy access.' },
    { id: 'mbna-fixed', provider: 'MBNA', name: 'One-year fixed savings', rate: 5.01, minimum: 1000, maximum: 750000, access: 'Fixed term', sourceUrl: 'https://www.mbna.co.uk/savings.html', terms: 'One-year fix; online opening, management by phone according to the source. No joint accounts. Verify the current product and banking licence.', summary: 'Part of the Lloyds banking group. A familiar brand does not remove the lock-in or the need to check the legal deposit-taking entity.' },
    { id: 'oaknorth-fixed', provider: 'OakNorth Bank', name: 'Two-year fixed savings', rate: 5.15, maximum: 500000, access: 'Fixed term', sourceUrl: 'https://oaknorth.co.uk/personal-savings/', terms: 'Two-year fix; interest at maturity. Online/app opening; joint accounts online only. Check access and funding window.', summary: 'A specialist UK bank. Compare its deposit protection and the maturity terms rather than relying on name recognition.' },
    { id: 'dfcapital-fixed', provider: 'DF Capital', name: 'Two-year fixed deposit', rate: 5.15, minimum: 1000, maximum: 250000, access: 'Fixed term', sourceUrl: 'https://www.dfcapital.bank/personal-savings/', terms: 'Two-year fix, with annual interest or interest at maturity according to the source. No joint accounts. Verify the current issue.', summary: 'A specialist banking provider. Check interest accessibility and tax timing as well as the fixed headline rate.' }
  ].map(({ id, provider, name, ...options }) => product(id, provider, name, 'Savings', options)),
  product('plum-isa', 'Plum', 'Easy-access cash ISA offer', 'Cash ISAs', { rate: 4.6, maximum: 20000, sourceUrl: 'https://withplum.com/cash-isa/', terms: 'New customers and new money: includes a one-year bonus. Lower rate for ISA transfers. Flexible ISA; check the underlying deposit bank and bonus conditions.', summary: 'An app-based savings service. Check where the money is actually deposited, plus transfer and bonus rules, rather than judging by the app name.' }),
  product('moneybox-isa', 'Moneybox', 'Cash ISA introductory offer', 'Cash ISAs', { rate: 4.58, minimum: 500, maximum: 20000, access: 'Limited access', sourceUrl: 'https://www.moneyboxapp.com/cash-isa', terms: 'New customers; includes a one-year bonus. More than three withdrawals a year reduces the rate to 0.75%. Not a flexible ISA.', summary: 'An app-based savings and investment service. The rate penalty makes this less suitable for repeated withdrawals; confirm the deposit bank.' }),
  product('charter-isa', 'Charter Savings Bank', 'Easy-access cash ISA', 'Cash ISAs', { rate: 4.26, maximum: 20000, sourceUrl: 'https://www.chartersavingsbank.co.uk/Products/ISAs', terms: 'Unlimited withdrawals, no introductory bonus noted; transfers accepted. Not flexible. Check the current account issue.', summary: 'An online savings bank. A straightforward access structure can be useful, but always compare the live rate and transfer rules.' }),
  product('shawbrook-isa', 'Shawbrook Bank', 'One-year fixed cash ISA', 'Cash ISAs', { rate: 4.94, minimum: 1000, maximum: 20000, access: 'Fixed term', sourceUrl: 'https://www.shawbrook.co.uk/savings/cash-isas/1-year-fixed-rate-cash-isa/', terms: 'One-year fix; early exit costs 90 days’ interest according to the comparison source. ISA transfers accepted at application; verify the live penalty.', summary: 'A specialist bank. A fixed cash ISA allows early exit under its terms, but a penalty can reduce interest or even capital.' }),
  product('nsandi-isa', 'NS&I', 'Direct ISA', 'Cash ISAs', { rate: 3.8, maximum: 20000, sourceUrl: 'https://www.nsandi.com/products/direct-isa', adapter: 'nsandi-aer', protection: '100% backed by HM Treasury, within product limits.', terms: 'Variable-rate cash ISA. Check transfer eligibility and withdrawal timings before opening.', summary: 'Government-backed cash savings. Compare flexibility and transfer rules as well as the interest rate.' }),
  ...[
    { id: 'trading-cash-isa', provider: 'Trading 212', name: 'Cash ISA new-customer offer', rate: 4.6, sourceUrl: 'https://www.trading212.com/isa?cash-isa=', terms: 'New customers: 3.6% variable plus a one-year 1% bonus. Prior-tax-year ISA transfers receive the lower 3.6% rate in the source. Flexible ISA; confirm qualifying offer conditions and the underlying banks.', summary: 'An investment-platform brand also offering a cash ISA. Keep the cash ISA separate from its investment/CFD accounts and check exactly how the cash is held.' },
    { id: 'tesco-cash-isa', provider: 'Tesco Bank', name: 'Easy-access cash ISA offer', rate: 4.2, sourceUrl: 'https://www.tescobank.com/savings/', terms: 'Flexible ISA. Source rate includes a one-year 3.15% bonus over a 1.05% variable base rate. Open online or by phone; verify the current issue and transfer rules.', summary: 'A familiar savings brand. Check the current Barclays Bank UK legal entity and shared protection, and remember the introductory bonus expires.' },
    { id: 'boi-cash-isa', provider: 'Bank of Ireland UK', name: 'Easy-access cash ISA offer', rate: 4.3, minimum: 100, sourceUrl: 'https://www.bankofirelanduk.com/personal/savings/', terms: 'Online opening; includes a one-year bonus. Transfers accepted; not a flexible ISA. Check the current issue and shared protection with partner-brand deposits.', summary: 'A banking group offering UK savings. Check the exact UK deposit-taking entity and any shared licence with other brands you use.' },
    { id: 'postoffice-cash-isa', provider: 'Post Office', name: 'Online cash ISA offer', rate: 4.25, minimum: 100, sourceUrl: 'https://www.postoffice.co.uk/savings', terms: 'Includes a one-year bonus. Transfers accepted; not flexible. Interest paid annually; check the actual bank holding your deposit.', summary: 'A recognisable brand with bank-provided savings. Review the bonus expiry and bank-level protection, not just the retail name.' },
    { id: 'leeds-cash-isa', provider: 'Leeds Building Society', name: 'Easy-access cash ISA', rate: 4.16, minimum: 1000, sourceUrl: 'https://www.leedsbuildingsociety.co.uk/savings/cash-isas/', terms: 'Account lasts one year, but the rate is variable. Transfers accepted; not flexible. Online opening and annual interest in the source.', summary: 'A well-known building society. Check the product maturity arrangements and rate rather than assuming all society accounts have the same terms.' },
    { id: 'natwest-fixed-isa', provider: 'NatWest', name: 'One-year fixed cash ISA', rate: 4.75, minimum: 1000, access: 'Fixed term', sourceUrl: 'https://www.natwest.com/savings/isa-overview.html', terms: 'One-year fix; source quotes a 90-day interest early-exit penalty. Transfers accepted. Check exact funding and withdrawal conditions.', summary: 'A high-street banking group. Familiarity may be useful, but the fixed-term penalty still makes this different from an easy-access ISA.' },
    { id: 'hodge-fixed-isa', provider: 'Hodge Bank', name: 'One-year fixed cash ISA', rate: 4.92, minimum: 1000, access: 'Fixed term', sourceUrl: 'https://hodgebank.co.uk/savings/', terms: 'One-year fix; source quotes a 90-day interest penalty and no transfers in. Monthly or maturity interest options; check live terms.', summary: 'A specialist bank. Transfer eligibility is an important limitation if you want to move an existing ISA rather than add new money.' },
    { id: 'oaknorth-fixed-isa', provider: 'OakNorth Bank', name: 'One-year fixed cash ISA', rate: 4.91, access: 'Fixed term', sourceUrl: 'https://oaknorth.co.uk/personal-savings/', terms: 'One-year fix; source quotes a 90-day interest early-exit penalty. Transfers accepted. Interest at maturity; check the current issue.', summary: 'A specialist bank offering both savings and ISAs. A small rate difference may not outweigh withdrawal penalties or a slow transfer.' }
  ].map(({ id, provider, name, ...options }) => product(id, provider, name, 'Cash ISAs', options)),
  product('premium', 'NS&I', 'Premium Bonds', 'Premium Bonds', { rate: 4.35, rateKind: 'Prize fund', minimum: 25, maximum: 50000, sourceUrl: 'https://www.nsandi.com/products/premium-bonds', adapter: 'nsandi-prize', protection: '100% backed by HM Treasury, within the £50,000 holding limit.', terms: 'No interest and no guaranteed winnings. The prize fund rate is an average across all bonds. Withdrawals normally take 3–5 days; bonds must qualify for the draw.', summary: 'The government-backed provider of Premium Bonds. Suitable to research for the prize structure, not for a predictable monthly or yearly income.' }),
  ...[
    ['vanguard-isa', 'Vanguard', 'Self-managed ISA', 'https://www.vanguardinvestor.co.uk/what-we-offer/fees-explained', '£4/month below £32,000; 0.15% a year above (maximum £375). Fund costs extra.', 'Own-brand funds and ETFs only. Simple investment range; the minimum platform fee weighs more heavily on smaller balances.'],
    ['trading-isa', 'Trading 212', 'Stocks & shares ISA', 'https://www.trading212.com/isa', 'No platform or share-dealing fee in the comparison source; 0.15% FX fee. Other charges may apply.', 'Shares and ETFs, not traditional funds. Low headline fees do not make investments low risk; avoid confusing ISA investing with leveraged CFDs.'],
    ['engine-isa', 'InvestEngine', 'DIY ETF ISA', 'https://investengine.com/isa/', 'DIY platform fee reported as zero; ETF costs and spreads still apply. Managed service fees differ.', 'ETF-focused platform rather than individual shares. Compare the DIY and managed services separately.'],
    ['ajbell-isa', 'AJ Bell', 'Stocks & shares ISA', 'https://www.ajbell.co.uk/isa', 'Platform fee reported as 0.25% a year; dealing and fund costs can apply. Check caps and regular-investing terms.', 'A broad investment platform offering funds, ETFs and shares. Range and service are useful to compare alongside total fees.']
  ].map(([id, provider, name, sourceUrl, fees, summary]) => product(id, provider, name, 'Stocks & shares ISAs', { risk: 'Investment', rateKind: 'None', access: 'Sell investments', maximum: 20000, sourceUrl, fees, summary, editorialUrl: investingGuide, protection: investmentProtection, terms: 'An ISA is a tax wrapper, not a guaranteed return. Allow time for selling and settling investments. Fees are a dated comparison snapshot, not automatically refreshed.' })),
  product('global-fund', 'Vanguard', 'FTSE Global All Cap Index Fund', 'Funds & ETFs', { risk: 'Investment', rateKind: 'None', access: 'Sell investments', sourceUrl: 'https://www.vanguardinvestor.co.uk/what-we-offer/all-products', editorialUrl: investingGuide, protection: investmentProtection, fees: 'Fund charge plus any platform fee. Read the current key investor information for the exact share class.', summary: 'A global equity index fund example, not a buy recommendation. Diversification reduces single-company dependence, but does not prevent losses.', terms: 'Traditional fund with exposure to many global companies. Research country concentration, currency risk, ongoing charges and the risk indicator.' }),
  product('global-etf', 'Vanguard', 'FTSE All-World UCITS ETF (VWRP)', 'Funds & ETFs', { risk: 'Investment', rateKind: 'None', access: 'Sell investments', sourceUrl: 'https://www.vanguardinvestor.co.uk/what-we-offer/etf-products', editorialUrl: investingGuide, protection: investmentProtection, fees: 'ETF ongoing charges, trading spread and possible platform or dealing fees. Verify the current factsheet.', summary: 'A diversified equity ETF example. Accumulation units reinvest dividends; exchange trading still carries market risk.', terms: 'Global shares ETF, not a savings account. Check the ticker, currency, share class and key information before investing.' }),
  ...[
    ['ulvr', 'Unilever', 'Unilever (ULVR) research', 'https://www.unilever.com/investors/', 'Consumer-goods company. A familiar brand name is not evidence that its share price is good value.'],
    ['ng', 'National Grid', 'National Grid (NG.) research', 'https://www.nationalgrid.com/investors', 'Energy-network company. Regulation, debt, funding needs and dividend changes can affect shareholders.']
  ].map(([id, provider, name, sourceUrl, summary]) => product(id, provider, name, 'Individual shares', { risk: 'Investment', rateKind: 'None', access: 'Sell investments', sourceUrl, summary, editorialUrl: investingGuide, protection: investmentProtection, fees: 'Broker dealing, FX and applicable transaction taxes may apply.', terms: 'Research example only; not a stock pick, price tracker or buy/sell signal. A single company can lose most or all of its value. Read results and consider diversification.' })),
  ...[
    ['moneybox-lisa', 'Moneybox', 'Cash Lifetime ISA', 'https://www.moneyboxapp.com/lifetime-isa', 'Cash Lifetime ISA provider. Compare its actual deposit bank, current interest and bonus conditions.'],
    ['ajbell-lisa', 'AJ Bell', 'Stocks & shares Lifetime ISA', 'https://www.ajbell.co.uk/lifetime-isa', 'Investment Lifetime ISA provider. Both market losses and withdrawal charges can reduce the amount you get back.']
  ].map(([id, provider, name, sourceUrl, summary]) => product(id, provider, name, 'Lifetime ISAs', { risk: id === 'ajbell-lisa' ? 'Investment' : 'Cash', rateKind: 'None', access: 'Restricted purpose', maximum: 4000, sourceUrl, summary, editorialUrl: 'https://www.gov.uk/lifetime-isa', fees: 'Check current provider fees, rate and any investment costs.', protection: id === 'ajbell-lisa' ? investmentProtection : cashProtection, terms: 'Normally open aged 18–39; up to £4,000 annual contributions count towards your overall ISA allowance, with a 25% government bonus. Qualifying first home (up to £450,000, account open 12 months) or age 60+. Other withdrawals normally incur a 25% charge on the whole withdrawal: this can take some of your original money.' }))
];

export const initialMarket = { schemaVersion: 1, lastAttemptAt: null, lastSuccessfulRateCheckAt: null, products: catalogue, history: [] };