const savingsGuide = 'https://www.moneysavingexpert.com/savings/savings-accounts-best-interest/';
const isaGuide = 'https://www.moneysavingexpert.com/savings/best-cash-isa/';
const investingGuide = 'https://www.moneysavingexpert.com/savings/stocks-shares-isas/';
const checked = '2026-10-05';
const cashProtection = 'Eligible deposits: FSCS up to £120,000 per person, per authorised institution. Shared licences count together; verify the named bank before depositing.';
const investmentProtection = 'No protection against market losses. FSCS investment protection may apply to eligible firm failures, not falling prices. Check the product structure.';

function product(id, provider, name, category, options) {
  const isa = category.includes('ISAs');
  const isaOptions = isa ? { ...options, maximum: null, annualContributionLimit: category === 'Lifetime ISAs' ? 4000 : 20000 } : options;
  return { id, provider, name, category, risk: 'Cash', rate: null, rateKind: 'AER', minimum: 1, maximum: null, bonusMonths: 12, access: 'Easy access', protection: cashProtection, rateCheckedAt: checked, termsReviewedAt: checked, checkStatus: 'manual', fees: 'No account fee noted in the source; confirm current terms.', reviewUrl: `https://uk.trustpilot.com/search?query=${encodeURIComponent(provider)}`, editorialUrl: category === 'Cash ISAs' ? isaGuide : savingsGuide, ...isaOptions };
}

export const catalogue = [
  product('cynergy', 'Cynergy Bank', 'Online Easy Access Account', 'Savings', { rate: 4.55, maximum: 1000000, sourceUrl: 'https://www.cynergybank.co.uk/personal/online-easy-access-account', adapter: 'cynergy', terms: 'Variable rate includes a 12-month bonus. Unlimited withdrawals; online management. Check the current issue and bonus before opening.', summary: 'An online savings bank. Worth comparing for unrestricted access, but the introductory bonus needs a calendar reminder.' }),
  product('cahoot', 'Cahoot', 'Sunny Day Saver', 'Savings', { rate: 5, maximum: 3000, sourceUrl: 'https://www.cahoot.com/products-and-services/cahoot-sunny-day-saver', adapter: 'cahoot', terms: 'Up to £3,000 only. Variable rate; the account lasts 12 months. Cahoot is part of Santander, so check shared protection.', summary: 'Santander’s online banking brand. The small balance cap means the headline rate cannot apply to a whole £10,000 lump sum.' }),
  product('zopa', 'Zopa Bank', 'Bonus savings offer', 'Savings', { rate: 4.56, access: 'Limited access', maximum: 50000, sourceUrl: 'https://www.zopa.com/smart-saver', terms: 'New customers; open Smart Saver first. Introductory offer falls to 2% after more than three withdrawals a year. Verify offer availability.', summary: 'A digital bank with app-managed savings. The withdrawal restriction is the key drawback for money you may need often.' }),
  product('union-one', 'Union Bank of India UK', 'One-year fixed deposit', 'Savings', { rate: 5.12, minimum: 1000, maximum: 480000, access: 'Fixed term', sourceUrl: 'https://www.unionpremierbond.unionbankofindiauk.co.uk/Index.aspx', terms: 'Lock away for one year. Interest at maturity. Not suitable for emergency savings; verify the UK entity and deposit terms.', summary: 'The UK banking subsidiary, not the same protection arrangement as an overseas account. Check the exact legal entity and access terms.' }),
  product('close-two', 'Close Brothers', 'Two-year fixed-rate bond', 'Savings', { rate: 5.16, minimum: 10000, maximum: 2000000, access: 'Fixed term', sourceUrl: 'https://www.closesavings.co.uk/personal/savings-accounts/fixed-rate-bond/2-year', terms: 'Two-year commitment; £10,000 minimum. Annual interest paid away; withdrawals normally unavailable during the term.', summary: 'A specialist banking group. The minimum deposit and two-year lock matter more than a small rate advantage if you need access.' }),
  product('birmingham-notice', 'Birmingham Bank', '95-day notice savings', 'Savings', { rate: 4.4, minimum: 5000, maximum: 250000, access: 'Notice', sourceUrl: 'https://www.birminghambank.com/', terms: 'Give 95 days’ notice to withdraw; minimum £5,000. Confirm the live account issue and notice rules.', summary: 'A specialist bank rather than a household high-street name. Notice savings cannot replace immediately available emergency cash.' }),
  product('castle-notice', 'Castle Trust Bank', '120-day notice savings', 'Savings', { rate: 4.2, minimum: 1000, maximum: 500000, access: 'Notice', sourceUrl: 'https://www.castletrust.co.uk/savings', terms: 'Give 120 days’ notice to withdraw. Variable rate; check the live issue.', summary: 'A specialist savings provider. Only consider this access type for money you can plan to withdraw well in advance.' }),
  product('nsandi-saver', 'NS&I', 'Direct Saver', 'Savings', { rate: 3.75, maximum: 2000000, sourceUrl: 'https://www.nsandi.com/products/direct-saver', adapter: 'nsandi-aer', protection: '100% backed by HM Treasury, within the product’s balance limits.', terms: 'Variable rate, yearly interest. Withdrawals are not necessarily same-day; check processing times.', summary: 'Government-backed savings. The trade-off may be a lower rate than commercial savings accounts.' }),
  product('plum-isa', 'Plum', 'Easy-access cash ISA offer', 'Cash ISAs', { rate: 4.6, maximum: 20000, sourceUrl: 'https://withplum.com/cash-isa/', terms: 'New customers and new money: includes a one-year bonus. Lower rate for ISA transfers. Flexible ISA; check the underlying deposit bank and bonus conditions.', summary: 'An app-based savings service. Check where the money is actually deposited, plus transfer and bonus rules, rather than judging by the app name.' }),
  product('moneybox-isa', 'Moneybox', 'Cash ISA introductory offer', 'Cash ISAs', { rate: 4.58, minimum: 500, maximum: 20000, access: 'Limited access', sourceUrl: 'https://www.moneyboxapp.com/cash-isa', terms: 'New customers; includes a one-year bonus. More than three withdrawals a year reduces the rate to 0.75%. Not a flexible ISA.', summary: 'An app-based savings and investment service. The rate penalty makes this less suitable for repeated withdrawals; confirm the deposit bank.' }),
  product('charter-isa', 'Charter Savings Bank', 'Easy-access cash ISA', 'Cash ISAs', { rate: 4.26, maximum: 20000, sourceUrl: 'https://www.chartersavingsbank.co.uk/Products/ISAs', terms: 'Unlimited withdrawals, no introductory bonus noted; transfers accepted. Not flexible. Check the current account issue.', summary: 'An online savings bank. A straightforward access structure can be useful, but always compare the live rate and transfer rules.' }),
  product('shawbrook-isa', 'Shawbrook Bank', 'One-year fixed cash ISA', 'Cash ISAs', { rate: 4.94, minimum: 1000, maximum: 20000, access: 'Fixed term', sourceUrl: 'https://www.shawbrook.co.uk/savings/cash-isas/1-year-fixed-rate-cash-isa/', terms: 'One-year fix; early exit costs 90 days’ interest according to the comparison source. ISA transfers accepted at application; verify the live penalty.', summary: 'A specialist bank. A fixed cash ISA allows early exit under its terms, but a penalty can reduce interest or even capital.' }),
  product('nsandi-isa', 'NS&I', 'Direct ISA', 'Cash ISAs', { rate: 3.8, maximum: 20000, sourceUrl: 'https://www.nsandi.com/products/direct-isa', adapter: 'nsandi-aer', protection: '100% backed by HM Treasury, within product limits.', terms: 'Variable-rate cash ISA. Check transfer eligibility and withdrawal timings before opening.', summary: 'Government-backed cash savings. Compare flexibility and transfer rules as well as the interest rate.' }),
  product('premium', 'NS&I', 'Premium Bonds', 'Premium Bonds', { rate: 4.35, rateKind: 'Prize fund', minimum: 25, maximum: 50000, sourceUrl: 'https://www.nsandi.com/products/premium-bonds', adapter: 'nsandi-prize', protection: '100% backed by HM Treasury, within the £50,000 holding limit.', terms: 'No interest and no guaranteed winnings. The prize fund rate is an average across all bonds. Withdrawals normally take 3–5 days; bonds must qualify for the draw.', summary: 'The government-backed provider of Premium Bonds. Suitable to research for the prize structure, not for a predictable monthly or yearly income.' }),
  ...[
    ['vanguard-isa', 'Vanguard', 'Self-managed ISA', 'https://www.vanguardinvestor.co.uk/what-we-offer/fees-explained', '£4/month below £32,000; 0.15% a year above (maximum £375). Fund costs extra.', 'Own-brand funds and ETFs only. Simple investment range; the minimum platform fee weighs more heavily on smaller balances.'],
    ['trading-isa', 'Trading 212', 'Stocks & shares ISA', 'https://www.trading212.com/isa', 'No platform or share-dealing fee in the comparison source; 0.15% FX fee. Other charges may apply.', 'Shares and ETFs, not traditional funds. Low headline fees do not make investments low risk; avoid confusing ISA investing with leveraged CFDs.'],
    ['engine-isa', 'InvestEngine', 'DIY ETF ISA', 'https://investengine.com/isa/', 'DIY platform fee reported as zero; ETF costs and spreads still apply. Managed service fees differ.', 'ETF-focused platform rather than individual shares. Compare the DIY and managed services separately.'],
    ['ajbell-isa', 'AJ Bell', 'Stocks & shares ISA', 'https://www.ajbell.co.uk/isa', 'Platform fee reported as 0.25% a year; dealing and fund costs can apply. Check caps and regular-investing terms.', 'A broad investment platform offering funds, ETFs and shares. Range and service are useful to compare alongside total fees.']
  ].map(([id, provider, name, sourceUrl, fees, summary]) => product(id, provider, name, 'Stocks & shares ISAs', { risk: 'Investment', rateKind: 'None', access: 'Sell investments', maximum: 20000, sourceUrl, fees, summary, editorialUrl: investingGuide, protection: investmentProtection, terms: 'An ISA is a tax wrapper, not a guaranteed return. Allow time for selling and settling investments. Fees are a dated comparison snapshot, not automatically refreshed.' })),
  product('global-fund', 'Vanguard', 'FTSE Global All Cap Index Fund', 'Funds & ETFs', { risk: 'Investment', rateKind: 'None', access: 'Sell investments', sourceUrl: 'https://www.vanguardinvestor.co.uk/what-we-offer/all-products', editorialUrl: investingGuide, protection: investmentProtection, fees: 'Fund charge plus any platform fee. Read the current key investor information for the exact share class.', summary: 'A global equity index fund example, not a buy recommendation. Diversification reduces single-company dependence, but does not prevent losses.', terms: 'Traditional fund with exposure to many global companies. Research country concentration, currency risk, ongoing charges and the risk indicator.' }),
  product('global-etf', 'Vanguard', 'FTSE All-World UCITS ETF (VWRP)', 'Funds & ETFs', { risk: 'Investment', rateKind: 'None', access: 'Sell investments', sourceUrl: 'https://www.vanguardinvestor.co.uk/what-we-offer/etf-products', editorialUrl: investingGuide, protection: investmentProtection, fees: 'ETF ongoing charges, trading spread and possible platform or dealing fees. Verify the current factsheet.', summary: 'A diversified equity ETF example. Accumulation units reinvest dividends; exchange trading still carries market risk.', terms: 'Global shares ETF, not a savings account. Check the ticker, currency, share class and key information before investing.' }),
  ...[
    ['ulvr', 'Unilever', 'Unilever (ULVR) research', 'https://www.unilever.com/investors/', 'Consumer-goods company. A familiar brand name is not evidence that its share price is good value.'],
    ['ng', 'National Grid', 'National Grid (NG.) research', 'https://www.nationalgrid.com/investors', 'Energy-network company. Regulation, debt, funding needs and dividend changes can affect shareholders.']
  ].map(([id, provider, name, sourceUrl, summary]) => product(id, provider, name, 'Individual shares', { risk: 'Investment', rateKind: 'None', access: 'Sell investments', sourceUrl, summary, editorialUrl: investingGuide, protection: investmentProtection, fees: 'Broker dealing, FX and applicable transaction taxes may apply.', terms: 'Research example only; not a stock pick, price tracker or buy/sell signal. A single company can lose most or all of its value. Read results and consider diversification.' })),
  ...[
    ['moneybox-lisa', 'Moneybox', 'Cash Lifetime ISA', 'https://www.moneyboxapp.com/lifetime-isa', 'Cash Lifetime ISA provider. Compare its actual deposit bank, current interest and bonus conditions.'],
    ['ajbell-lisa', 'AJ Bell', 'Stocks & shares Lifetime ISA', 'https://www.ajbell.co.uk/lifetime-isa', 'Investment Lifetime ISA provider. Both market losses and withdrawal charges can reduce the amount you get back.']
  ].map(([id, provider, name, sourceUrl, summary]) => product(id, provider, name, 'Lifetime ISAs', { risk: id === 'ajbell-lisa' ? 'Investment' : 'Cash', rateKind: 'None', access: 'Restricted purpose', maximum: 4000, sourceUrl, summary, editorialUrl: 'https://www.gov.uk/lifetime-isa', fees: 'Check current provider fees, rate and any investment costs.', protection: id === 'ajbell-lisa' ? investmentProtection : cashProtection, terms: 'Normally open aged 18–39; up to £4,000 annual contributions count towards your overall ISA allowance, with a 25% government bonus. Qualifying first home (up to £450,000, account open 12 months) or age 60+. Other withdrawals normally incur a 25% charge on the whole withdrawal: this can take some of your original money.' }))
];

export const initialMarket = { schemaVersion: 1, lastAttemptAt: null, lastSuccessfulRateCheckAt: null, products: catalogue, history: [] };